### ISSUE TITLE
Regression: zope.password.testing.setUpPasswordManagers() fails with ZopeXMLConfigurationError ("unknown directive")

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.password#15]
I'm using `zope.app.testing.setup.placelessSetUp()` in zodbbrowser's unit tests.  It now fails with

```
Traceback (most recent call last):
  File "/home/mg/.cache/buildout/eggs/unittest2-1.1.0-py2.7.egg/unittest2/case.py", line 67, in testPartExecutor
    yield
  File "/home/mg/.cache/buildout/eggs/unittest2-1.1.0-py2.7.egg/unittest2/case.py", line 621, in run
    self.setUp()
  File "/home/mg/src/zodbbrowser/src/zodbbrowser/tests/test_value.py", line 281, in setUp
    setup.placelessSetUp()
  File "/home/mg/.cache/buildout/eggs/zope.app.testing-3.10.0-py2.7.egg/zope/app/testing/placelesssetup.py", line 40, in setUp
    setUpPasswordManagers()
  File "/home/mg/.cache/buildout/eggs/zope.password-4.3.0-py2.7.egg/zope/password/testing.py", line 81, in setUpPasswordManagers
    xmlconfig.file('configure.zcml', zope.password)
  File "/home/mg/.cache/buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/xmlconfig.py", line 498, in file
    include(context, name, package)
  File "/home/mg/.cache/buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/xmlconfig.py", line 402, in include
    processxmlfile(f, context)
  File "/home/mg/.cache/buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/xmlconfig.py", line 295, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 354, in start_element_ns
    AttributesNSImpl(newattrs, qnames))
  File "/home/mg/.cache/buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/xmlconfig.py", line 213, in startElementNS
    None, sys.exc_info()[2])
  File "/home/mg/.cache/buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/xmlconfig.py", line 204, in startElementNS
    self.context.begin(name, data, info)
  File "/home/mg/.cache/buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/config.py", line 342, in begin
    self.stack.append(self.stack[-1].contained(__name, __data, __info))
  File "/home/mg/.cache/buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/config.py", line 509, in contained
    return RootStackItem.contained(self, name, data, info)
  File "/home/mg/.cache/buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/config.py", line 473, in contained
    factory = self.context.factory(self.context, name)
  File "/home/mg/.cache/buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/config.py", line 311, in factory
    raise ConfigurationError("Unknown directive", ns, n)
ZopeXMLConfigurationError: File "/home/mg/.cache/buildout/eggs/zope.password-4.3.0-py2.7.egg/zope/password/configure.zcml", line 83.4
    ConfigurationError: ('Unknown directive', u'http://namespaces.zope.org/zope', u'class')
```

This is a regression since zope.password 4.2.0.  The diff between the two versions shows that `setUpPasswords` was changed from calling `provideUtiliy()` to invoking `xmlconfig.file('configure.zcml')`.

**Comment by jamadden** [comment]
Interesting, thanks for the report. `setUpPasswordManagers` is tested here...but the tests must not have `zope.security` installed as the use of `<class>`  is hidden under a `zcml:condition=installed zope.security`. I'll work on a fix.

**Comment by jamadden** [comment]
It also shows up on Travis: https://travis-ci.org/zopefoundation/zope.principalregistry/jobs/270815599 I'd like to get #16 merged and released to fix that.
