### ISSUE TITLE
Tests fail with pypy-3.6-v7.2.0 and newer

### ISSUE THREAD

**Issue by cjwatson** [zopefoundation/zope.password#20]
The test suite fails with pypy-3.6-v7.2.0 and newer (pypy-3.6-v7.1.1 worked fine).  Sample output with pypy-3.6-v7.3.2:

```
Failure in test CryptPasswordManager (zope.password.legacy)
Failed doctest test for zope.password.legacy.CryptPasswordManager
  File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 36, in CryptPasswordManager

----------------------------------------------------------------------
File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 52, in zope.password.legacy.CryptPasswordManager
Failed example:
    encoded = manager.encodePassword(password, salt="..")
Exception raised:
    Traceback (most recent call last):
      File "/home/cjwatson/src/python/pyenv/versions/pypy3.6-7.3.2/lib-python/3/doctest.py", line 1332, in __run
        compileflags, 1), test.globs)
      File "<doctest zope.password.legacy.CryptPasswordManager[6]>", line 1, in <module>
        encoded = manager.encodePassword(password, salt="..")
      File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 118, in encodePassword
        return '{CRYPT}%s' % crypt(password, salt)
      File "/home/cjwatson/src/python/pyenv/versions/pypy3.6-7.3.2/lib-python/3/crypt.py", line 47, in crypt
        return _crypt.crypt(word, salt)
      File "/home/cjwatson/src/python/pyenv/versions/pypy3.6-7.3.2/lib_pypy/_crypt/__init__.py", line 19, in crypt
        word = word.encode('ascii')
    UnicodeEncodeError: 'ascii' codec can't encode character '\u0410' in position 6: ordinal not in range(128)
----------------------------------------------------------------------
File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 53, in zope.password.legacy.CryptPasswordManager
Failed example:
    encoded
Exception raised:
    Traceback (most recent call last):
      File "/home/cjwatson/src/python/pyenv/versions/pypy3.6-7.3.2/lib-python/3/doctest.py", line 1332, in __run
        compileflags, 1), test.globs)
      File "<doctest zope.password.legacy.CryptPasswordManager[7]>", line 1, in <module>
        encoded
    NameError: name 'encoded' is not defined
----------------------------------------------------------------------
File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 55, in zope.password.legacy.CryptPasswordManager
Failed example:
    manager.match(encoded)
Exception raised:
    Traceback (most recent call last):
      File "/home/cjwatson/src/python/pyenv/versions/pypy3.6-7.3.2/lib-python/3/doctest.py", line 1332, in __run
        compileflags, 1), test.globs)
      File "<doctest zope.password.legacy.CryptPasswordManager[8]>", line 1, in <module>
        manager.match(encoded)
    NameError: name 'encoded' is not defined
----------------------------------------------------------------------
File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 57, in zope.password.legacy.CryptPasswordManager
Failed example:
    manager.checkPassword(encoded, password)
Exception raised:
    Traceback (most recent call last):
      File "/home/cjwatson/src/python/pyenv/versions/pypy3.6-7.3.2/lib-python/3/doctest.py", line 1332, in __run
        compileflags, 1), test.globs)
      File "<doctest zope.password.legacy.CryptPasswordManager[9]>", line 1, in <module>
        manager.checkPassword(encoded, password)
    NameError: name 'encoded' is not defined
----------------------------------------------------------------------
File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 63, in zope.password.legacy.CryptPasswordManager
Failed example:
    isinstance(encoded, str)
Exception raised:
    Traceback (most recent call last):
      File "/home/cjwatson/src/python/pyenv/versions/pypy3.6-7.3.2/lib-python/3/doctest.py", line 1332, in __run
        compileflags, 1), test.globs)
      File "<doctest zope.password.legacy.CryptPasswordManager[10]>", line 1, in <module>
        isinstance(encoded, str)
    NameError: name 'encoded' is not defined
----------------------------------------------------------------------
File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 71, in zope.password.legacy.CryptPasswordManager
Failed example:
    manager.checkPassword(encoded, password + u"wrong")
Exception raised:
    Traceback (most recent call last):
      File "/home/cjwatson/src/python/pyenv/versions/pypy3.6-7.3.2/lib-python/3/doctest.py", line 1332, in __run
        compileflags, 1), test.globs)
      File "<doctest zope.password.legacy.CryptPasswordManager[11]>", line 1, in <module>
        manager.checkPassword(encoded, password + u"wrong")
    NameError: name 'encoded' is not defined
----------------------------------------------------------------------
File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 76, in zope.password.legacy.CryptPasswordManager
Failed example:
    manager.checkPassword(encoded, 'completely wrong')
Exception raised:
    Traceback (most recent call last):
      File "/home/cjwatson/src/python/pyenv/versions/pypy3.6-7.3.2/lib-python/3/doctest.py", line 1332, in __run
        compileflags, 1), test.globs)
      File "<doctest zope.password.legacy.CryptPasswordManager[12]>", line 1, in <module>
        manager.checkPassword(encoded, 'completely wrong')
    NameError: name 'encoded' is not defined
----------------------------------------------------------------------
File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 89, in zope.password.legacy.CryptPasswordManager
Failed example:
    encoded
Expected:
    '{CRYPT}erz50QD3gv4Dw'
Got:
    "{CRYPT}b'erz50QD3gv4Dw'"
----------------------------------------------------------------------
File "/home/cjwatson/src/python/zope.password/.tox/pypy3/site-packages/zope/password/legacy.py", line 92, in zope.password.legacy.CryptPasswordManager
Failed example:
    manager.checkPassword(encoded, password)
Expected:
    True
Got:
    False
```

I believe this is actually a PyPy bug, and I've filed [issue 3378](https://foss.heptapod.net/pypy/pypy/-/issues/3378) with them about it.  However, I thought it would be helpful to file it here for visibility as well, since it'll come up if anyone tries to get zope.password running on GitHub Actions (indeed, I ran into it there when attempting to port zopefoundation/zopetoolkit's CI jobs).

It's also possible that if it takes too long to get this fixed properly then we may need to mark PyPy3 as unsupported again, though that doesn't seem ideal.  (7.2.0 was released on 2019-10-14 and as far as I can tell I'm the first person to run into this, so I guess either zope.password isn't much used on PyPy3 or else its users don't keep up to date with upstream PyPy3 releases?)

**Comment by mgedmin** [comment]
I'm not opposed to implementing a workaround in zope.password code?  E.g. we could try to always pass bytes to crypt.crypt(), and decode the result conditionally based on the type rather than on Python version?  I might be speaking nonsense, since I haven't looked at the code to see what it's doing currently.

**Comment by mgedmin** [comment]
> we could try to always pass bytes to crypt.crypt()

Ah, no, CPython 3.x requires the first crypt() argument to be str, not bytes.

**Comment by cjwatson** [comment]
This has been fixed in PyPy upstream now.  They seem to release a few times a year, so maybe we can just hold our breaths.

**Comment by icemac** [comment]
This issue is marked with `wontfix` but still open. Should we close it or wait until the next PyPy release including the fix`

**Comment by mgedmin** [comment]
No objections to closing it now.
